POST gerarqrcodepix.com.br/api/v1?nome=Igor Resende Pinheiro&cidade=Recife&saida=br&txid=PresenteCasorioRaquelIgor&chave=+5581998212130
# POST gerarqrcodepix.com.br/api/v1?nome=Igor Resende Pinheiro&cidade=Recife&saida=qr&txid=PresenteCasorioRaquelIgor&chave=+5581998212130

###