name: Create Release

permissions:
    contents: write

on:
    push:
        branches:
            - main
        paths:
            - "package.json"

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22"

            - name: Get package version
              id: get_version
              run: |
                  VERSION=$(jq -r '.version' package.json)
                  echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ env.VERSION }}
                  release_name: Release ${{ env.VERSION }}
                  draft: false
                  prerelease: false

            - name: Set up Firebase CLI
              run: |
                  curl -sL https://firebase.tools | bash

            - name: Install
              run: |
                  npm install

            - name: Build
              run: |
                  npm run build:prod

            - name: Deploy to Firebase
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
              run: |
                  firebase deploy --only hosting --token "$FIREBASE_TOKEN"
